/**
 * Created by Vincent P. Minde  on 3/2/16.
 */
//Sample command nodejs start -url http://localhost:8080/dhis2 -dhis http://localhost:8080/dhis2 -u kmbwilo -p DHIS2014 -o /tmp/output.pdf -mu mailname -mp password -mh localhost
var path = require('path')
var childProcess = require('child_process')
var phantomjs = require('phantomjs')
var binPath = phantomjs.path;

console.log(process.argv);
var outputFile = "/tmp/output.pdf",dhisServer = "http://localhost:8080/dhis2",
username = "", password = "",mailUser = "",mailPassword = "", mailHost = "localhost", urlToConvert = "http://localhost:8080/dhis2";
//Evaluate arguments
for(var index = 0;index <  process.argv.length; index++){
    var commandArgument = process.argv[index];
    if(commandArgument == "-dhis"){
        dhisServer = process.argv[index + 1];
    }else if(commandArgument == "-u"){
        username = process.argv[index + 1];
    }else if(commandArgument == "-p"){
        password = process.argv[index + 1];
    }else if(commandArgument == "-o"){
        outputFile = process.argv[index + 1];
    }else if(commandArgument == "-mu"){
        mailUser = process.argv[index + 1];
    }else if(commandArgument == "-mp"){
        mailPassword = process.argv[index + 1];
    }else if(commandArgument == "-mh"){
        mailHost = process.argv[index + 1];
    }else if(commandArgument == "-url"){
        urlToConvert = process.argv[index + 1];
    }
}
console.log(urlToConvert);

var childArgs = [
    path.join(__dirname, 'rasterize.js'),
    urlToConvert,//'https://hmisportal.moh.go.tz/hmisportal/#/home',
    outputFile
];
var postfixsever   = require(__dirname + "/postfixsever");

//Excecute phantomjs to convert url to
childProcess.execFile(binPath, childArgs, function(err, stdout, stderr) {
    if(err){
        console.log("Failed to fetch url",err);
    }else{
        //Fetch the group of user to get the report
        var request = require('request'),
            url = dhisServer +"/api/userGroups/FZ5zdaTkOFJ.json?fields=users[email]",
            auth = "Basic " + new Buffer(username + ":" + password).toString("base64");

        request(
            {
                url : url,
                headers : {
                    "Authorization" : auth
                }
            },
            function (error, response, body) {
                if(error){
                    console.log(error);
                }else{
                    console.log(body);
                    //Parse the body into json object
                    var json = JSON.parse(body);
                    var emails = "";
                    //Extract emails
                    for (var user in json.users){
                        if(user == 0){
                            emails = json.users[user].email;
                        }else {
                            emails += ", " + json.users[user].email;
                        }
                    }
                    //Send the email
                    postfixsever.postfixSend(
                        {
                            user: mailUser,
                            password: mailPassword,
                            host: mailHost,
                            ssl: false
                        },
                        {
                            msg: "Reports Generated By DHIS 2",
                            from: "vincent@localhost",
                            to: emails,
                            subject: "Awesome",
                            attachment: [
                                {path: outputFile, type: "application/pdf", name: "report.pdf"}
                            ]
                    },function(result){
                        console.log("Mail results",result);
                    })
                }

                // Do more stuff with 'body' here
            }
        );
    }
})
